// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crjgcefmdlnbcowppxqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNyamdjZWZtZGxuYmNvd3BweHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1ODA0ODQsImV4cCI6MjA4NjE1NjQ4NH0.raO1tHiJZ-IOVjv4iqka0_err57I7nNaFWGATqkBcJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});